### ISSUE TITLE
"./images/logo.svg" instead of "/images/logo.svg" in main.phel line 14

### ISSUE THREAD

**Issue by kloimhardt** [phel-lang/phel-scaffolding#12]
currently, the elephant does not show up when phel-scaffolding is ftp'd onto somedomain.com and
http://somedomain.com/phel-scaffolding/src/web/index.php
is opened in the browser.

The proposal in the topic fixes this.

**Comment by JesusValeraDev** [comment]
Changed @kloimhardt.
Thanks!
