### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by jenshaase** [phel-lang/phel-scaffolding#2]
The Readme says that Docker is optional. However, the Requirements section only shows the docker way. 

I would split it in two section. The first section is without Docker. The second section is with Docker. Even if you have to repeat a lot of stuff. I will be easier for beginners in my opinion. Especially, if new users don't have experience with docker.

**Comment by Chemaclass** [comment]
@jenshaase, I added some docu about installation without docker here: https://github.com/Chemaclass/phel-scaffolding/commit/649a673418522d93ca129cc1995d10181d519a3f

**Comment by jenshaase** [comment]
Looks good now. Only this one is not correct:

```
If you create new namespaces, remember to execute the composer dump-autoload to auto-generate them inside the PhelRuntime.
```

You only have to do that if you change the `loader` section in `composer.json` but not if you create a new file with a new namespace.
