### ISSUE TITLE
Run with a server (web app development)

### ISSUE THREAD

**Issue by jenshaase** [phel-lang/phel-scaffolding#3]
The section "With a PHP Server" of the Getting Started Guide is missing here. 
See https://phel-lang.org/documentation/getting-started/

It just shows only the way on how to run a single file but not how to start a server and develop a basic web app.

**Comment by JesusValeraDev** [comment]
I will try.

**Comment by JesusValeraDev** [comment]
Done; https://github.com/phel-lang/phel-scaffolding/commit/d6002927c6082f3071789c7a4e592f55383df89e

![image](https://user-images.githubusercontent.com/6381924/105579865-65843d00-5d89-11eb-8da4-ea03fec3894b.png)
