### ISSUE TITLE
Remove composer.lock?

### ISSUE THREAD

**Issue by jenshaase** [phel-lang/phel-scaffolding#5]
After running `composer install` on a fresh checkout. I got this message:
```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
```

Should we maybe remove composer.lock from this repository?

**Comment by Chemaclass** [comment]
Oh... good point. I would say yes. The only real dependency from this repo should be the latest "phel-lang". 
I would say yes. You can remove it in order to get rid of that warning message.
